import { NAV_ITEM_TYPE_COLLAPSE, NAV_ITEM_TYPE_ITEM } from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'
import { ADMIN, FACULTY, INDUSTRY, LEARNER } from '@/constants/roles.constant'

const collaborateNav: NavigationTree[] = [
  // industry
  {
    key: 'nav.industries',
    path: '/collaborate/my-analysis/on-the-agenda',
    title: 'Dashboard',
    translateKey: 'nav.Industry.item3',
    icon: 'myWall',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [ADMIN, INDUSTRY],
    subMenu: [],
    groups: ['collaborate'],
  },
  {
    key: 'nav.industries.talentPool',
    path: '/industry/talent-pool',
    title: 'Talent Pool',
    translateKey: 'nav.Industry.talentPool',
    icon: 'talentPool',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [ADMIN, INDUSTRY],
    subMenu: [],
    groups: ['collaborate'],
  },
  {
    key: 'nav.industries.jobs',
    path: '/industry/jobs',
    title: 'Jobs',
    translateKey: 'nav.Industry.item4',
    icon: 'internship',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [ADMIN, INDUSTRY],
    subMenu: [],
    groups: ['collaborate'],
  },
  {
    key: 'nav.industries.analytics',
    path: '/industry/analytics',
    title: 'Analytics',
    translateKey: 'nav.Industry.analytics',
    icon: 'analytics',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [ADMIN, INDUSTRY],
    subMenu: [],
    groups: ['collaborate'],
  },

  // learner & faculty
  {
    key: 'nav.collaborate',
    path: '/collaborate',
    title: 'Home',
    translateKey: 'nav.home',
    icon: 'house',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [LEARNER, FACULTY],
    subMenu: [],
    groups: ['collaborate'],
  },

  {
    key: 'nav.collaborate.infocus',
    path: '/infocus',
    title: 'InFocus',
    translateKey: 'nav.infocust',
    icon: 'infocus',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [LEARNER, FACULTY, INDUSTRY, ADMIN],
    subMenu: [
      {
        key: 'nav.collaborate.infocus.creators',
        path: '/collaborate/infocus?tab=Creators',
        title: 'Creators',
        translateKey: 'nav.infocust.creators',
        icon: 'creators',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [LEARNER, FACULTY, INDUSTRY, ADMIN],
        subMenu: [],
        groups: ['collaborate'],
      },
      {
        key: 'nav.collaborate.industries',
        path: '/collaborate/infocus?tab=Industries',
        title: 'Industries',
        translateKey: 'nav.industries',
        icon: 'industries',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [LEARNER, FACULTY, INDUSTRY, ADMIN],
        subMenu: [],
        groups: ['collaborate'],
      },
      {
        key: 'nav.collaborate.institute',
        path: '/collaborate/infocus?tab=Institutes',
        title: 'Institutes',
        translateKey: 'nav.institute',
        icon: 'learningMenu',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [LEARNER, FACULTY, INDUSTRY, ADMIN],
        subMenu: [],
        groups: ['collaborate'],
      }
    ],
    groups: ['collaborate'],
  },

  {
    key: 'Nav.OnTheAgenda',
    path: '/on-the-agenda',
    title: 'On the Agenda',
    translateKey: 'nav.onTheAgenda',
    icon: 'onTheAgenda',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [LEARNER, FACULTY, INDUSTRY, ADMIN],
    subMenu: [
      // Masterclass, Workshops, Industry Visits, Competitions, Immersion Programs
      {
        key: 'nav.collaborate.onTheAgenda.masterclass',
        path: 'agenda/masterclass?category=Masterclass',
        title: 'Masterclass',
        translateKey: 'nav.onTheAgenda.masterclass',
        icon: 'masterclass',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [LEARNER, FACULTY, INDUSTRY, ADMIN],
        subMenu: [],
        groups: ['collaborate'],
      },
      {
        key: 'nav.collaborate.onTheAgenda.workshops',
        path: 'agenda/workshops?category=Workshops',
        title: 'Workshops',
        translateKey: 'nav.onTheAgenda.workshops',
        icon: 'workshops',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [LEARNER, FACULTY, INDUSTRY, ADMIN],
        subMenu: [],
        groups: ['collaborate'],
      },
      {
        key: 'nav.collaborate.onTheAgenda.industryVisits',
        path: 'agenda/industry-visits?category=Industry Visits',
        title: 'Industry Visits',
        translateKey: 'nav.onTheAgenda.industryVisits',
        icon: 'industryVisits',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [LEARNER, FACULTY, INDUSTRY, ADMIN],
        subMenu: [],
        groups: ['collaborate'],
      },
      {
        key: 'nav.collaborate.onTheAgenda.competitions',
        path: 'agenda/competitions?category=Competitions',
        title: 'Competitions',
        translateKey: 'nav.onTheAgenda.competitions',
        icon: 'competitions',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [LEARNER, FACULTY, INDUSTRY, ADMIN],
        subMenu: [],
        groups: ['collaborate'],
      },
    ],
    groups: ['collaborate'],
  },
  {
    key: 'nav.MustAttend',
    path: '/must-attend',
    title: 'Must Attend',
    translateKey: 'nav.mustAttend',
    icon: 'events',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [LEARNER, FACULTY, INDUSTRY, ADMIN],
    subMenu: [
      {
        key: 'nav.collaborate.must-attend.community-meetups',
        path: '/must-attend/community-meetups?category=Community%20Meetup',
        title: 'Creators Meetups',
        translateKey: 'nav.mustAttend.communityMeetups',
        icon: 'communityMeetups',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [LEARNER, FACULTY, INDUSTRY, ADMIN],
        subMenu: [],
        groups: ['collaborate'],
      },
      {
        key: 'nav.collaborate.must-attend.flagship-events',
        path: '/must-attend/flagship-events?category=Flagship%20Events',
        title: 'enCODE',
        translateKey: 'nav.mustAttend.flagshipEvents',
        icon: 'flagshipEvents',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [LEARNER, FACULTY, INDUSTRY, ADMIN],
        subMenu: [],
        groups: ['collaborate'],
      },
      {
        key: 'nav.collaborate.must-attend.internship-placement-drive',
        path: '/must-attend/career-drive?category=Career Drive',
        title: 'Career Drive',
        translateKey: 'nav.mustAttend.internshipPlacementDrive',
        icon: 'internshipPlacementDrive',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [LEARNER, FACULTY, INDUSTRY, ADMIN],
        subMenu: [],
        groups: ['collaborate'],
      },
      {
        key: 'nav.collaborate.onTheAgenda.immersionPrograms',
        path: '/must-attend/immersion-programs?category=Immersion Programs',
        title: 'Immersion Programs',
        translateKey: 'nav.onTheAgenda.immersionPrograms',
        icon: 'immersionPrograms',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [LEARNER, FACULTY, INDUSTRY, ADMIN],
        subMenu: [],
        groups: ['collaborate'],
      }
    ],
    groups: ['collaborate'],
  },
  {
    key: 'nav.collaborate.Opportunities',
    path: '/opportunities',
    title: 'Jobs/Internships',
    translateKey: 'nav.opportunities',
    icon: 'internship',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [LEARNER],
    subMenu: [],
    groups: ['collaborate'],
  },
  {
    key: 'nav.collaborate.topIndustries',
    path: '/collaborate/industries',
    title: 'Industries',
    translateKey: 'nav.opportunities',
    icon: 'industries',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [LEARNER, ADMIN, FACULTY, INDUSTRY],
    subMenu: [],
    groups: ['collaborate'],
  },

  // {
  //     key: 'Internship',
  //     path: '/internship',
  //     title: 'Internship/Jobs'
  //     translateKey: 'nav.internship',
  //     icon: 'internship',
  //     type: NAV_ITEM_TYPE_ITEM,
  //     authority: [LEARNER],
  //     subMenu: [],
  //     groups: ['collaborate'],
  // },
  // {
  //     key: 'Event',
  //     path: '/events',
  //     title: 'Event',
  //     translateKey: 'nav.event',
  //     icon: 'event',
  //     type: NAV_ITEM_TYPE_ITEM,
  //     authority: [LEARNER],
  //     subMenu: [],
  //     groups: ['collaborate'],
  // },

  // FACULTY

  // {
  //     key: 'Events',
  //     path: '/manage-events',
  //     title: 'Events',
  //     translateKey: 'nav.events',
  //     icon: 'events',
  //     type: NAV_ITEM_TYPE_ITEM,
  //     authority: [FACULTY],
  //     subMenu: [],
  //     groups: ['connect', 'collaborate'],
  // },
  {
    key: 'collaborate.StudentQueries',
    path: '/student-queries',
    title: 'Student Queries',
    translateKey: 'nav.studentQueries',
    icon: 'userSearch',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [FACULTY],
    subMenu: [],
    groups: ['collaborate'],
  },
]

export default collaborateNav