import {
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'
import { ADMIN, FACULTY, INDUSTRY, LEARNER } from '@/constants/roles.constant'

const createGroupNav: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/create',
        title: 'Dashboard',
        translateKey: 'nav.dashboard',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [LEARNER, FACULTY, ADMIN, INDUSTRY],
        subMenu: [],
        groups: ['create'],
    },
    //  {
    //     key: 'analyticsDashboard',
    //     path: '/analytics-dashboard',
    //     title: 'Analytics Dashboard',
    //     translateKey: 'nav.analyticsDashboard',
    //     icon: 'analyticsDashboard',
    //     type: NAV_ITEM_TYPE_ITEM,
    //     authority: [FACULTY, ADMIN],
    //     subMenu: [],
    //     groups: ['create'],
    // },
    {
        key: 'mySpace',
        path: '/my-space',
        title: 'My Space',
        translateKey: 'nav.mySpace',
        icon: 'mySpace',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [LEARNER, FACULTY, ADMIN, INDUSTRY],
        subMenu: [
            {
                key: 'myCourses',
                path: '/my-courses',
                title: 'My Courses',
                translateKey: 'nav.myCourses',
                icon: 'myCourses',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [LEARNER, FACULTY, ADMIN, INDUSTRY],
                subMenu: [],
                groups: ['create'],
            },
            {
                key: 'myClasses',
                path: '/my-classes',
                title: 'Classes',
                translateKey: 'nav.enrolledCourses',
                icon: 'myCourses',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [LEARNER, FACULTY, ADMIN, INDUSTRY],
                subMenu: [],
                groups: ['create'],
            },
            {
                key: 'Nav.Mentoring.MyMentors',
                path: '/mentoring/my-mentors?is_refresh=true',
                title: 'Mentors',
                translateKey: 'nav.recommendedCourses',
                icon: 'myCourses',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [LEARNER, FACULTY, ADMIN, INDUSTRY],
                subMenu: [],
                groups: ['create'],
            },
            {
                key: 'nav.myspace.resources',
                path: '/my-space/resource-hub',
                title: 'Resource Hub',
                translateKey: 'nav.exploreAllCourses',
                icon: 'myCourses',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [LEARNER, FACULTY, ADMIN, INDUSTRY],
                subMenu: [],
                groups: ['create'],
            },
            {
                key: 'nav.myspace.payment',
                path: '/purchase-history',
                title: 'Purchase History',
                translateKey: 'nav.purchase-history',
                icon: 'myCourses',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [LEARNER, FACULTY, ADMIN, INDUSTRY],
                subMenu: [],
                groups: ['create'],
            },
        ],
        groups: ['create'],
    },
    {
        key: 'recommended',
        path: '/recommended',
        title: 'Recommended',
        translateKey: 'nav.recommended',
        icon: 'recommended',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [LEARNER, FACULTY, ADMIN, INDUSTRY],
        subMenu: [
            {
                key: 'recommendedCourses',
                path: '/courses/recommended',
                title: 'Courses',
                translateKey: 'nav.allCourses',
                icon: 'myCourses',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [LEARNER, FACULTY, ADMIN, INDUSTRY],
                subMenu: [],
                groups: ['create'],
            },
            {
                key: 'Nav.Mentoring.Recommended',
                path: '/mentoring/recommended?is_refresh=true',
                title: 'Mentors',
                translateKey: 'nav.recommendedCourses',
                icon: 'myCourses',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [LEARNER, FACULTY, ADMIN, INDUSTRY],
                subMenu: [],
                groups: ['create'],
            },
            {
                key: 'nav.recommended.resources',
                path: '/recommended/resource-hub',
                title: 'Resource Hub',
                translateKey: 'nav.exploreAllCourses',
                icon: 'myCourses',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [LEARNER, FACULTY, ADMIN, INDUSTRY],
                subMenu: [],
                groups: ['create'],
            },

        ],
        groups: ['create'],
    },
    {
        key: 'explore',
        path: '/explore',
        title: 'Explore',
        translateKey: 'nav.explore',
        icon: 'explore',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [LEARNER, FACULTY, ADMIN, INDUSTRY],
        subMenu: [
            {
                key: 'exploreAllCourses',
                path: '/courses/explore',
                title: 'Courses',
                translateKey: 'nav.allCourses',
                icon: 'myCourses',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [LEARNER, FACULTY, ADMIN, INDUSTRY],
                subMenu: [],
                groups: ['create'],
            },
            {
                key: 'Nav.Mentoring.Explore',
                path: '/mentoring/explore?is_refresh=true',
                title: 'Mentors',
                translateKey: 'nav.recommendedCourses',
                icon: 'myCourses',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [LEARNER, FACULTY, ADMIN, INDUSTRY],
                subMenu: [],
                groups: ['create'],
            },
            {
                key: 'exploreAllResources',
                path: '/explore/resource-hub',
                title: 'Resource Hub',
                translateKey: 'nav.exploreAllCourses',
                icon: 'myCourses',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [LEARNER, FACULTY, ADMIN, INDUSTRY],
                subMenu: [],
                groups: ['create'],
            },

        ],
        groups: ['create'],
    },
    {
        key: 'Calendar',
        path: '/calendar',
        title: 'Calendar',
        translateKey: 'nav.calendar',
        icon: 'calendar',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [LEARNER, FACULTY, ADMIN, INDUSTRY],
        subMenu: [],
        groups: ['create'],
    },
    // faculty
    {
        key: 'Activity',
        path: '/activity',
        title: 'Activity',
        translateKey: 'nav.activity',
        icon: 'classes',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [FACULTY],
        subMenu: [
            {
                key: 'subjects',
                path: '/dashboard/instructor?tab=courses-sessions#courses-section',
                title: 'Subjects',
                translateKey: 'nav.subjects',
                icon: 'assignment',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [FACULTY],
                subMenu: [],
                groups: ['create'],
            },
            {
                key: 'sessions',
                path: '/dashboard/instructor?tab=courses-sessions#sessions-section',
                title: 'Sessions',
                translateKey: 'nav.sessions',
                icon: 'sessions',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [FACULTY],
                subMenu: [],
                groups: ['create'],
            },
            // {
            //     key: 'Assessment',
            //     path: '/assessments',
            //     title: 'Assessment',
            //     translateKey: 'nav.assessment',
            //     icon: 'quiz',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [FACULTY],
            //     subMenu: [],
            //     groups: ['create'],
            // },
            {
                key: 'assignment',
                path: '/dashboard/instructor?tab=assignments#assignments-section',
                title: 'Assignments',
                translateKey: 'nav.assignments',
                icon: 'assignment',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [FACULTY],
                subMenu: [],
                groups: ['create'],
            },
            {
                key: 'userSearch',
                path: '/user-search',
                title: 'User Search',
                translateKey: 'nav.userSearch',
                icon: 'userSearch',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [FACULTY],
                subMenu: [],
                groups: ['create'],
            },
        ],
        groups: ['create'],
    },
    {
        key: 'StudentQueries',
        path: '/student-queries',
        title: 'Student Queries',
        translateKey: 'nav.studentQueries',
        icon: 'userSearch', // Using an existing icon similar to search/queries
        type: NAV_ITEM_TYPE_ITEM,
        authority: [FACULTY],
        subMenu: [],
        groups: ['create'],
    },
]

export default createGroupNav
